
import com.mostc.pftt.results.PhpResultPackWriter;
def describe() {
	"Load local MySql server for use with PHPT tests and Applications"
}

def scenarios() {
	new MySQLScenario(new LocalHost());
}

import com.mostc.pftt.model.core.PhpBuild;
import com.mostc.pftt.model.core.PhptSourceTestPack;

// ext/pdo/tests/pdo_test.inc uses getenv() instead of $_ENV
// MySQLScenario uses ENV vars to pass configuration information to PHPT tests
//    using getenv() on Apache or other web servers might not read all ENV vars
//    should use $_ENV instead: modify `mysql` PHPTs to use $_ENV instead.
//
def processPHPTTestPack(PhptSourceTestPack test_pack, PhpResultPackWriter writer, PhpBuild build) {
	LocalHost host = new LocalHost();
	String php_code = host.readFileAsString(test_pack.getSourceDirectory()+"/ext/pdo/tests/pdo_test.inc");
	
	if (php_code.contains("function getenv")) {
		// already modified
		System.out.println("local_mysql: already modified pdo_test.inc");
		return;
	} else {
		
		php_code = """<?php

function getenv(\$name) {
		// generated by PFTT's local_mysql config
		return \$_ENV[\$name];
}

?>
$php_code
"""
	
		php_file = test_pack.getSourceDirectory()+"/ext/pdo/tests/pdo_test.inc";
	
		System.out.println("local_mysql: modifying $php_file for MySQL scenario");
		host.saveTextFile(php_file, php_code);
	}
}
