source 'http://rubygems.org' # LATER? local cache of dependencies (on PFTT Server)

gem 'rspec', '~> 2.3.0'
gem 'ZenTest', '~> 4.4.2'
gem 'activesupport'
#gem 'i18n' # required by ActiveSupport but bundler fails to see that dependency

gem 'mysql'
gem 'sqlite3-ruby'
gem 'typed-array'
gem 'net-ssh'
gem 'net-sftp'

gem 'pony'

gem 'abstract_class'

gem 'activerecord'

gem 'nokogiri'

gem 'rufus-scheduler'